### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by gunthercox** [LitleCo/litle-sdk-for-python#5]
Currently, the `litle-sdk-for-python` isn't compatible with Python 3. I was wondering if there was any plans in your roadmap to add this?

At the moment, my team is working to add Python 3 support to this library. Once completed, would there be any interest on your side in a pull request?

**Comment by amitvig22** [comment]
Thank you for reaching out to us, we would be very glad to accept a pull request once we are ready to support Python 3.

**Comment by gunthercox** [comment]
Great, we will keep you posted.

**Comment by kevin-brown** [comment]
Here's a quick overview of the changes required (so far)

- Python 3 is only supported by the latest version of [PyXB (1.2.4)](https://pypi.python.org/pypi/PyXB/1.2.4), so that will need to be upgraded.
  - The [`litleSdkPython.litleXmlFields` module](https://github.com/LitleCo/litle-sdk-for-python/blob/5099841fd4e95268d3fa53593f2d6d3e04a9f4a2/litleSdkPython/litleXmlFields.py) will need to be regenerated.
  - The base exception was renamed in PyXB 1.1.5, so the few places we catch that need to be updated. [[commit](https://github.com/Rediker-Software/litle-sdk-for-python/commit/5c6a390fd0261b2773a36a771b4ac2bc63dd4427), [commit](https://github.com/Rediker-Software/litle-sdk-for-python/commit/5a05817b1ee0b8741372b65d046e3176241b4230)]
- Any relative imports (there are a lot) will need to be [changed to absolute imports](http://stackoverflow.com/q/12172791/359284). [[commit]](https://github.com/Rediker-Software/litle-sdk-for-python/commit/2e3c97de15a1207ef93ad64e2c9013abb450a782)
- There are a few `bytes` changes as a result of the [new `io` module](https://docs.python.org/2/library/io.html).
- Dropping support for Python 2.5 (as a minimum). It doesn't look like this should be as much of an issue, as while there was Python 2.5 code in the library, there was also 2.6 code in there (that wasn't backwards compatible). [[commit]](https://github.com/Rediker-Software/litle-sdk-for-python/commit/5c6a390fd0261b2773a36a771b4ac2bc63dd4427)

And because we're testing on Windows, there were [a few changes required](https://github.com/Rediker-Software/litle-sdk-for-python/commit/dbf6351c28be7130df02876964aaf4f4e304a332) to get tests working.

**Comment by kefin** [comment]
Is there any update on Python 3 support for `litle-sdk-for-python`?

**Comment by gunthercox** [comment]
@kefin My team was unable to get the current code base updated to work with Python 3. It ended up being more efficient for us to generate the xml for the requests manually, rather than take the time to update the litle sdk for python ourselves.

**Comment by kefin** [comment]
Thanks for the update! That's the route we're going to take to use Python 3 with the Vantiv API.

**Comment by hickeroar** [comment]
What's the ETA on getting this dependency upgraded to support python3? This is a show stopper for an application my team I'm working on.

**Comment by hickeroar** [comment]
I'm working on a port to python3. I've successfully regenerated the xml fields using pyxbgen, and I've used 2to3 on the application to get it updated. I'm unsure if I'll be successful yet, but if I am I'll be sure to post about it here. However, I probably won't attempt to port the test suite to python3.

Best case scenario I'll have a fork people can pip-git install to have python3 support at the moment.

**Comment by kefin** [comment]
Here is an update on what I did for my project:

This Vantiv/Litle Python SDK is a mess -- especially the `litleXMLFields.py` auto-generated source file, which is unintelligible. Much of the code looks like it's written by folks who don't know much about Python and would rather use something else. I gave up on using it for our Python 3 project (it never worked) and ended up writing a small app from scratch as part of our Django project to format XML requests to talk to the Vantiv API directly, as suggested by @gunthercox.

From a maintenance point of view our custom simplified rewrite saves us a lot of headaches and is much easier to integrate with our project code. The savings on technical debt alone justified this approach.

Just a small heads up to those who are trying to work with this library -- you may be better off rolling your own glue code.

**Comment by kevin-brown** [comment]
As mentioned by @gunthercox, we decided to stop work on converting the SDK to Python 3 and instead are generating the requests manually.

Just a small note to the next person who tries to convert this over.

We _were_ able to get a Python 3 version of the SDK working. You can see [the progress we had here](https://github.com/Rediker-Software/litle-sdk-for-python/commits/py3), but ultimately we decided to stop working towards getting the test suite to pass when we realized the tests didn't match the xsd file. The "post generation" script attempted to override some of the decisions made in the xsd file, instead of fixing the issues in the xsd file itself. With the change in PyXB versions, this file no longer made the changes and modifying it to make it work seemed like a lost cause.

If anyone on the Litle/Vantiv team knows why the xsd file doesn't match the tests, that might be a good start.

**Comment by hickeroar** [comment]
@kefin Any chance of you open sourcing the library you wrote?

**Comment by kefin** [comment]
@hickeroar Unfortunately, the app was written as part of our internal payment processing system so we will not be opening sourcing it.

For our purposes, our project only needed a subset of the Vantiv transactions and options so I only implemented the transactions we needed -- e.g. no batch uploads, all online transactions, simple authorize, capture, sale, credit, void transactions with minimal element sets, etc. I based the code on the Ruby and PHP versions of the Litle SDK, which actually contain handwritten versions of the XML schema processing code (not auto-generated). I used `lxml` to convert Python objects to XML payload data to send to the Vantiv API.

For us, the simplified/custom library is much easier to test and maintain because of the smaller set of transactions and options and also minimal dependencies.

**Comment by hickeroar** [comment]
@kefin Thanks for the insight. If my python 3 conversion doesn't work I'll check out the ruby and php sdks.

**Comment by Houzl** [comment]
Please tryhttps://github.com/LitleCo/litle-sdk-for-python/tree/9.0v2

**Comment by Houzl** [comment]
Please try branch 9.0v2. It works for XML v9.10 
https://github.com/LitleCo/litle-sdk-for-python/tree/9.0v2

**Comment by kevin-brown** [comment]
> Please try branch 9.0v2. It works for XML v9.10

I'm not sure how that could possible be, considering [PyXB is pinned to 1.1.15](https://github.com/LitleCo/litle-sdk-for-python/blob/187ec46a22df7fa8ce2a8f8912e97b5b9af18474/setup.py#L13) and they didn't finish adding support for Python 3 until PyXB 1.2.4.

**Comment by litleSDK** [comment]
Hi Kevin,

Branch 9.0v2 is a new version of python SDK, which is using PyXB 1.2.5. It has been moved to a new repo at https://github.com/LitleCo/vantiv-sdkv2-for-python. Sorry for inconvenience.

Best,
Zhilong Hou
